### ISSUE TITLE
[Error]: SyntaxError: Missing parentheses in call to 'print'.

### ISSUE THREAD

**Issue by dillfrescott** [CompVis/latent-diffusion#200]
```
2022-12-03 04:56:07.830389: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2022-12-03 04:56:07.998958: E tensorflow/stream_executor/cuda/cuda_blas.cc:2981] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2022-12-03 04:56:08.689838: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2022-12-03 04:56:08.689947: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer_plugin.so.7'; dlerror: libnvinfer_plugin.so.7: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/lib64-nvidia
2022-12-03 04:56:08.689967: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Cannot dlopen some TensorRT libraries. If you would like to use Nvidia GPU with TensorRT, please make sure the missing libraries mentioned above are installed properly.
Traceback (most recent call last):
  File "scripts/knn2img.py", line 16, in <module>
    from ldm.util import instantiate_from_config, parallel_data_prefetch
  File "/usr/local/envs/ldm/lib/python3.8/site-packages/ldm.py", line 20
    print self.face_rec_model_path 
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(self.face_rec_model_path)?
ERROR conda.cli.main_run:execute(47): `conda run python scripts/knn2img.py --prompt a dog in a field` failed. (See above for error)
```

This is when running the command:

```
python scripts/knn2img.py --prompt "a dog in a field"
```

**Comment by theswerd** [comment]
+1
