### ISSUE TITLE
KeyError: 'Trying to restore training state but checkpoint contains only the model.

### ISSUE THREAD

**Issue by traveling121** [CompVis/latent-diffusion#221]
When I run main.py with ImageNet data and cin256 model, it shows as follows:

Traceback (most recent call last):
  File "/data/latent-diffusion-main/main.py", line 731, in <module>
    trainer.test(model, data)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in test
    results = self.__test_given_model(model, test_dataloaders)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 784, in __test_given_model
    results = self.fit(model)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 445, in fit
    results = self.accelerator_backend.train()
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 148, in train
    results = self.ddp_train(process_idx=self.task_idx, model=model)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/ddp_accelerator.py", line 279, in ddp_train
    self.trainer.train_loop.setup_training(model)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/training_loop.py", line 174, in setup_training
    self.trainer.checkpoint_connector.restore_weights(model)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 75, in restore_weights
    self.restore(self.trainer.resume_from_checkpoint, on_gpu=self.trainer.on_gpu)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 113, in restore
    self.restore_training_state(checkpoint)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/connectors/checkpoint_connector.py", line 157, in restore_training_state
    'Trying to restore training state but checkpoint contains only the model.'
KeyError: 'Trying to restore training state but checkpoint contains only the model. This is probably due to `ModelCheckpoint.save_weights_only` being set to `True`.'

Please tell me how to solve it ?

**Comment by SantiUsma** [comment]
Do you include the flag -r to resume your model? I had the same issue using the -r flag so I decided not use it and put a  model.load_state_dict(torch.load('path_to_model.ckpt')['state_dict']) right after model = instantiate_from_config(config.model) in the main.py script.

**Comment by CreamyLong** [comment]
> 



> Do you include the flag -r to resume your model? I had the same issue using the -r flag so I decided not use it and put a model.load_state_dict(torch.load('path_to_model.ckpt')['state_dict']) right after model = instantiate_from_config(config.model) in the main.py script.

This method works. But it is weird to use such way to do fine-tune.

**Comment by traveling121** [comment]
Thanks
