### ISSUE TITLE
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

### ISSUE THREAD

**Issue by Yoonho-Na** [CompVis/latent-diffusion#228]
Hi I'm facing the error while operating p_losses function.

> Traceback (most recent call last):
  File "main.py", line 720, in <module>
    trainer.fit(model, data)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 768, in fit
    self._call_and_handle_interrupt(
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 719, in _call_and_handle_interrupt
    return self.strategy.launcher.launch(trainer_fn, *args, trainer=self, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/strategies/launchers/subprocess_script.py", line 93, in launch
    return function(*args, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 809, in _fit_impl
    results = self._run(model, ckpt_path=self.ckpt_path)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1234, in _run
    results = self._run_stage()
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1321, in _run_stage
    return self._run_train()
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1343, in _run_train
    self._run_sanity_check()
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1411, in _run_sanity_check
    val_loop.run()
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/dataloader/evaluation_loop.py", line 153, in advance
    dl_outputs = self.epoch_loop.run(self._data_fetcher, dl_max_batches, kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 204, in run
    self.advance(*args, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 127, in advance
    output = self._evaluation_step(**kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/evaluation_epoch_loop.py", line 222, in _evaluation_step
    output = self.trainer._call_strategy_hook("validation_step", *kwargs.values())
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1763, in _call_strategy_hook
    output = fn(*args, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/strategies/ddp.py", line 347, in validation_step
    return self.model(*args, **kwargs)
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1040, in forward
    output = self._run_ddp_forward(*inputs, **kwargs)
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/nn/parallel/distributed.py", line 1000, in _run_ddp_forward
    return module_to_run(*inputs[0], **kwargs[0])
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yhn/.conda/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 93, in forward
    return self.module.validation_step(*inputs, **kwargs)
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/home/yhn/Meta_synthesis/Project/models/latent-diffusion/ldm/models/diffusion/ddpm.py", line 359, in validation_step
    _, loss_dict_no_ema = self.shared_step(batch)
  File "/home/yhn/Meta_synthesis/Project/models/latent-diffusion/ldm/models/diffusion/ddpm.py", line 867, in shared_step
    loss = self(x, c)
  File "/home/yhn/.local/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1194, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/yhn/Meta_synthesis/Project/models/latent-diffusion/ldm/models/diffusion/ddpm.py", line 879, in forward
    return self.p_losses(x, c, t, *args, **kwargs)
  File "/home/yhn/Meta_synthesis/Project/models/latent-diffusion/ldm/models/diffusion/ddpm.py", line 1030, in p_losses
    logvar_t = self.logvar[t].to(self.device)
RuntimeError: indices should be either on cpu or on the same device as the indexed tensor (cpu)

I'm trying to run the code on 4 GPUs.
How can I solve this error?
I have tried 
`logvar_t = self.logvar[t].to(self.device)`
to
`logvar_t = self.logvar[t].to('cpu')`
but it didn't work.

I'm not sure what is causing this error.
I have successfully trained autoencoderKL in my environment.
`kornia==0.6.4, pytorch-lightning==1.6.1, torch==1.13.1, ...`

**EDIT**
I tried using single GPU with `--gpus 0,`but it also showed same error

**Comment by Yoonho-Na** [comment]
**problem solved**
solved by setting device on self.logvar right before the error line


> self.logvar = self.logvar.to(self.device)
> logvar_t = self.logvar[t].to(self.device)

**Comment by maogewudi007** [comment]
> **problem solved** solved by setting device on self.logvar right before the error line
> 
> > self.logvar = self.logvar.to(self.device)
> > logvar_t = self.logvar[t].to(self.device)

Do you know the meaning of the self.logvar ?

**Comment by YuzheZhang-1999** [comment]
Is this caused by a different version of the package? Because this error will not be reported in a certain virtual environment.

Do you know which package may cause it?

**Comment by jacob-kang** [comment]
+1

**Comment by chiexplorer** [comment]
> Is this caused by a different version of the package? Because this error will not be reported in a certain virtual environment.
> 
> Do you know which package may cause it?
I encountered this issue on Windows 11. The key configurations are as follows:
python=3.8.5
torch=1.13.0+cu117
pytorch-lightning=1.4.2
