### ISSUE TITLE
Help: dependencies error

### ISSUE THREAD

**Issue by wnz27** [CompVis/latent-diffusion#252]
when i run: 
```
conda env create -f environment.yaml
```
but:
```
Collecting package metadata (repodata.json): done
Solving environment: failed

ResolvePackageNotFound:
  - cudatoolkit=11.0
```

**Comment by wnz27** [comment]
i change this to : `- cudatoolkit` and fix it 
but the lib scann can't install

**Comment by wnz27** [comment]
i install scann with source code and according to the prompt install other dependencies.

**Comment by wnz27** [comment]
then the scann need python version, see: https://github.com/google-research/google-research/tree/master/scann

**Comment by wnz27** [comment]
wait a moment, but i run : `python scripts/knn2img.py  --prompt "a happy bear reading a newspaper, oil on canvas"`
have error:
```
Traceback (most recent call last):
  File "scripts/knn2img.py", line 12, in <module>
    import scann
ModuleNotFoundError: No module named 'scann'
```

**Comment by KhawlahB** [comment]
Did you solve the problem of cudatoolkit? If yes, please let me know how you solved it.
I am facing the same problem.

**Comment by KhawlahB** [comment]
> wait a moment, but i run : `python scripts/knn2img.py --prompt "a happy bear reading a newspaper, oil on canvas"` have error:
> 
> ```
> Traceback (most recent call last):
>   File "scripts/knn2img.py", line 12, in <module>
>     import scann
> ModuleNotFoundError: No module named 'scann'
> ```

Did you solve the problem of cudatoolkit? 
```
ResolvePackageNotFound:
  - cudatoolkit=11.0
```
If yes, please let me know how you solved it.
I am facing the same problem.

@wnz27

**Comment by wnz27** [comment]
> > wait a moment, but i run : `python scripts/knn2img.py --prompt "a happy bear reading a newspaper, oil on canvas"` have error:
> > ```
> > Traceback (most recent call last):
> >   File "scripts/knn2img.py", line 12, in <module>
> >     import scann
> > ModuleNotFoundError: No module named 'scann'
> > ```
> 
> Did you solve the problem of cudatoolkit?
> 
> ```
> ResolvePackageNotFound:
>   - cudatoolkit=11.0
> ```
> 
> If yes, please let me know how you solved it. I am facing the same problem.
> 
> @wnz27

i dont fix it, you computer is new mac? i think its cpu arch problem may be

**Comment by KhawlahB** [comment]
> > > wait a moment, but i run : `python scripts/knn2img.py --prompt "a happy bear reading a newspaper, oil on canvas"` have error:
> > > ```
> > > Traceback (most recent call last):
> > >   File "scripts/knn2img.py", line 12, in <module>
> > >     import scann
> > > ModuleNotFoundError: No module named 'scann'
> > > ```
> > 
> > 
> > Did you solve the problem of cudatoolkit?
> > ```
> > ResolvePackageNotFound:
> >   - cudatoolkit=11.0
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > If yes, please let me know how you solved it. I am facing the same problem.
> > @wnz27
> 
> i dont fix it, you computer is new mac? i think its cpu arch problem may be

- It is a Macbook Pro 2019. What do you mean by cpu arch? What is the problem exactly? Can I solve it? or it will not work on my Mac totally?

- **Also, did you solve the problem of scann? that you mentioned here?** https://github.com/CompVis/latent-diffusion/issues/252#issuecomment-1482908852. https://github.com/CompVis/latent-diffusion/issues/252#issuecomment-1482894609

- **Moreover, did you find another GitHub code for Diffusion Models that works on Mac? If yes, please provide me with a Github link.**

Your collaboration is highly appreciated. 

@wnz27
