### ISSUE TITLE
TypeError: forward() got an unexpected keyword argument 'predicted_indices' When train the VQModel.

### ISSUE THREAD

**Issue by traveling121** [CompVis/latent-diffusion#256]
Traceback (most recent call last):
  File "/data/latent-diffusion-main/main.py", line 732, in <module>
    trainer.fit(model, data)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 445, in fit
    results = self.accelerator_backend.train()
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 64, in train
    results = self.train_or_test()
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/accelerator.py", line 66, in train_or_test
    results = self.trainer.train()
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 467, in train
    self.run_sanity_check(self.get_model())
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 659, in run_sanity_check
    _, eval_results = self.run_evaluation(test_mode=False, max_batches=self.num_sanity_val_batches)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/trainer.py", line 579, in run_evaluation
    output = self.evaluation_loop.evaluation_step(test_mode, batch, batch_idx, dataloader_idx)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/trainer/evaluation_loop.py", line 171, in evaluation_step
    output = self.trainer.accelerator_backend.validation_step(args)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 88, in validation_step
    output = self.__validation_step(args)
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/pytorch_lightning/accelerators/gpu_accelerator.py", line 96, in __validation_step
    output = self.trainer.model.validation_step(*args)
  File "/data/latent-diffusion-main/ldm/models/autoencoder.py", line 169, in validation_step
    log_dict = self._validation_step(batch, batch_idx)
  File "/data/latent-diffusion-main/ldm/models/autoencoder.py", line 181, in _validation_step
    predicted_indices=ind
  File "/data/latent-diffusion-main/venv/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
TypeError: forward() got an unexpected keyword argument 'predicted_indices'.

Could you please tell me what caused this issue and how to solve this problem?

**Comment by thesisfinitobitte** [comment]
Hi, did you solve the problem?

**Comment by zhangyl660** [comment]
Hi, did you solve the problem?

**Comment by nicolasfischoeder** [comment]
I am also getting this :(.

**Comment by nicolasfischoeder** [comment]
I fixed it by commenting out the predicted_indices parameters in the forward functions.

**Comment by traveling121** [comment]
Thanks~

**Comment by function2-llx** [comment]
According to the config file, the `VQLPIPSWithDiscriminator` class from the `taming` package is used, e.g.,

https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/models/first_stage_models/vq-f16/config.yaml#L24-L25

which is defined [here](https://github.com/CompVis/taming-transformers/blob/3ba01b241669f5ade541ce990f7650a3b8f65318/taming/modules/losses/vqperceptual.py#L76-L77) and does not have a `predicted_indices` parameter. 

While the `VQLPIPSWithDiscriminator` class in this repository does have a `predicted_indices` parameter:

https://github.com/CompVis/latent-diffusion/blob/a506df5756472e2ebaf9078affdde2c4f1502cd4/ldm/modules/losses/vqperceptual.py#L98-L99

Perhaps the mismatched code is released.

**Comment by 58191554** [comment]
Yes there is a version problem, now the VQLPIPSWithDiscriminator has that parameter/
