### ISSUE TITLE
how to train inpainting model with my own datasets

### ISSUE THREAD

**Issue by duxiying0369** [CompVis/latent-diffusion#265]
hello,you're doing a great job.I'm new to deep learning, so I'd like to ask this project for more detailed steps in training the inpainting model, such as data set settings, config, training steps, can you give me some help? Thank you very much.

**Comment by dreamlychina** [comment]
> hello,you're doing a great job.I'm new to deep learning, so I'd like to ask this project for more detailed steps in training the inpainting model, such as data set settings, config, training steps, can you give me some help? Thank you very much.

你找到训练代码了？？

**Comment by duxiying0369** [comment]
> > hello,you're doing a great job.I'm new to deep learning, so I'd like to ask this project for more detailed steps in training the inpainting model, such as data set settings, config, training steps, can you give me some help? Thank you very much.
> 
> 你找到训练代码了？？

没有跑通，现在没做这个方向了

**Comment by fittiing** [comment]
Hello, may I ask if you are running inpaint. Did this error occur again while copying the file? Can you help me solve it?

Traceback (most recent call last):
  File "scripts/inpaint.py", line 60, in <module>
    model = instantiate_from_config(config.model)
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/diffusion/ddpm.py", line 460, in __init__
    self.instantiate_first_stage(first_stage_config)
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/diffusion/ddpm.py", line 503, in instantiate_first_stage
    model = instantiate_from_config(config)
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/autoencoder.py", line 266, in __init__
    super().__init__(embed_dim=embed_dim, *args, **kwargs)
  File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/autoencoder.py", line 39, in __init__
    self.quantize = VectorQuantizer(n_embed, embed_dim, beta=0.25,
TypeError: __init__() got an unexpected keyword argument 'remap'

**Comment by csuhwq0421** [comment]
> 

hello，I meet the same issue with you.May I ask if you have solved this problem? and how to solve it？

**Comment by csuhwq0421** [comment]
> Hello, may I ask if you are running inpaint. Did this error occur again while copying the file? Can you help me solve it?
> 
> Traceback (most recent call last): File "scripts/inpaint.py", line 60, in model = instantiate_from_config(config.model) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/util.py", line 85, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict())) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/diffusion/ddpm.py", line 460, in **init** self.instantiate_first_stage(first_stage_config) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/diffusion/ddpm.py", line 503, in instantiate_first_stage model = instantiate_from_config(config) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/util.py", line 85, in instantiate_from_config return get_obj_from_str(config["target"])(**config.get("params", dict())) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/autoencoder.py", line 266, in **init** super().**init**(embed_dim=embed_dim, *args, **kwargs) File "/root/autodl-tmp/latent-diffusion-main/scripts/ldm/models/autoencoder.py", line 39, in **init** self.quantize = VectorQuantizer(n_embed, embed_dim, beta=0.25, TypeError: **init**() got an unexpected keyword argument 'remap'

hello , I met the same problem with you. May I ask if you solved this problem and how to solve it？

**Comment by fittiing** [comment]
![~7}(IDB0 `UN~JJLRL08OZ3](https://github.com/CompVis/latent-diffusion/assets/126837170/0c60be86-d9e6-434d-8df0-87cc0b7dca7e)
