### ISSUE TITLE
FileNotFoundError:[Errno 2] No such file or directory: '/tmp/a306397ccf9c2ead27155983c254227c0fd938e2.torrent'

### ISSUE THREAD

**Issue by 27yw** [CompVis/latent-diffusion#321]

**Comment by 27yw** [comment]
when I want to run this command:python main.py --base configs/autoencoder/autoencoder_kl_8x8x64.yaml -t --gpus 0,
I got these errors:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 25, in __init__
    contents = open("/tmp/" + hash + '.torrent', 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/a306397ccf9c2ead27155983c254227c0fd938e2.torrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/envs/ldm/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/root/miniconda3/envs/ldm/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 665, in <module>
    data.prepare_data()
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/root/code/ldm/main.py", line 187, in prepare_data
    instantiate_from_config(data_cfg)
  File "/root/code/ldm/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/code/ldm/ldm/data/imagenet.py", line 377, in __init__
    super().__init__(**kwargs)
  File "/root/code/ldm/ldm/data/imagenet.py", line 292, in __init__
    self.base = self.get_base()
  File "/root/code/ldm/ldm/data/imagenet.py", line 382, in get_base
    dset = ImageNetTrain(process_images=False,)
  File "/root/code/ldm/ldm/data/imagenet.py", line 148, in __init__
    super().__init__(**kwargs)
  File "/root/code/ldm/ldm/data/imagenet.py", line 33, in __init__
    self._prepare()
  File "/root/code/ldm/ldm/data/imagenet.py", line 171, in _prepare
    atpath = at.get(self.AT_HASH, datastore=self.root)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/academictorrents.py", line 19, in get
    torrent = Torrent(at_hash, datastore)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 29, in __init__
    contents = self.get_from_url()
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 103, in get_from_url
    response = urlopen(url, timeout=5).read()
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>.


The full terminal:
python main.py --base configs/autoencoder/autoencoder_kl_8x8x64.yaml -t --gpus 0,
2023-10-22 01:53:18.060895: I tensorflow/core/util/port.cc:110] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-10-22 01:53:18.130692: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-10-22 01:53:19.332462: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
Global seed set to 23
Running on GPUs 0,
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
Working with z of shape (1, 64, 8, 8) = 4096 dimensions.
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
making attention of type 'vanilla' with 512 in_channels
loaded pretrained LPIPS loss from taming/modules/autoencoder/lpips/vgg.pth
Monitoring val/rec_loss as checkpoint metric.
Merged modelckpt-cfg: 
{'target': 'pytorch_lightning.callbacks.ModelCheckpoint', 'params': {'dirpath': 'logs/2023-10-22T01-53-20_autoencoder_kl_8x8x64/checkpoints', 'filename': '{epoch:06}', 'verbose': True, 'save_last': True, 'monitor': 'val/rec_loss', 'save_top_k': 3}}
GPU available: True, used: True
TPU available: False, using: 0 TPU cores
IPU available: False, using: 0 IPUs
Preparing dataset ILSVRC2012_train in /root/.cache/autoencoders/data/ILSVRC2012_train
Traceback (most recent call last):
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 25, in __init__
    contents = open("/tmp/" + hash + '.torrent', 'rb').read()
FileNotFoundError: [Errno 2] No such file or directory: '/tmp/a306397ccf9c2ead27155983c254227c0fd938e2.torrent'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1350, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/root/miniconda3/envs/ldm/lib/python3.8/http/client.py", line 921, in connect
    self.sock = self._create_connection(
  File "/root/miniconda3/envs/ldm/lib/python3.8/socket.py", line 808, in create_connection
    raise err
  File "/root/miniconda3/envs/ldm/lib/python3.8/socket.py", line 796, in create_connection
    sock.connect(sa)
OSError: [Errno 99] Cannot assign requested address

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "main.py", line 665, in <module>
    data.prepare_data()
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/pytorch_lightning/core/datamodule.py", line 428, in wrapped_fn
    fn(*args, **kwargs)
  File "/root/code/ldm/main.py", line 187, in prepare_data
    instantiate_from_config(data_cfg)
  File "/root/code/ldm/ldm/util.py", line 85, in instantiate_from_config
    return get_obj_from_str(config["target"])(**config.get("params", dict()))
  File "/root/code/ldm/ldm/data/imagenet.py", line 377, in __init__
    super().__init__(**kwargs)
  File "/root/code/ldm/ldm/data/imagenet.py", line 292, in __init__
    self.base = self.get_base()
  File "/root/code/ldm/ldm/data/imagenet.py", line 382, in get_base
    dset = ImageNetTrain(process_images=False,)
  File "/root/code/ldm/ldm/data/imagenet.py", line 148, in __init__
    super().__init__(**kwargs)
  File "/root/code/ldm/ldm/data/imagenet.py", line 33, in __init__
    self._prepare()
  File "/root/code/ldm/ldm/data/imagenet.py", line 171, in _prepare
    atpath = at.get(self.AT_HASH, datastore=self.root)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/academictorrents.py", line 19, in get
    torrent = Torrent(at_hash, datastore)
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 29, in __init__
    contents = self.get_from_url()
  File "/root/miniconda3/envs/ldm/lib/python3.8/site-packages/academictorrents/Torrent.py", line 103, in get_from_url
    response = urlopen(url, timeout=5).read()
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 502, in _call_chain
    result = func(*args)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1379, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/root/miniconda3/envs/ldm/lib/python3.8/urllib/request.py", line 1353, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [Errno 99] Cannot assign requested address>

how to fix this ?

**Comment by whumaker1** [comment]
Hello, I also have the same problem,  did you solve it?

**Comment by daqiudi** [comment]
> Hello, I also have the same problem, did you solve it?

hello, do you deal with it?

**Comment by chkzhao** [comment]
I met the same problem when I tried to train my own VAE model, and I found I forgot to change the data path in the config file to my data_path. After changing the data path, the problem was solved.
