### ISSUE TITLE
pip fails while installing requirements

### ISSUE THREAD

**Issue by eyacov** [CompVis/latent-diffusion#348]
Hey
I'm trying to install the model using conda env create -f environment.yaml as written in the readme, but I'm getting this error
`Channels:
 - pytorch
 - defaults
Platform: linux-64
Collecting package metadata (repodata.json): done
Solving environment: done

Downloading and Extracting Packages:

Preparing transaction: done
Verifying transaction: done
Executing transaction: | By downloading and using the CUDA Toolkit conda packages, you accept the terms and conditions of the CUDA End User License Agreement (EULA): https://docs.nvidia.com/cuda/eula/index.html

done
Installing pip dependencies: | Ran pip subprocess with arguments:
['/home/user/anaconda3/envs/ldm/bin/python', '-m', 'pip', 'install', '-U', '-r', '/media/user/Daten/localization/latent-diffusion/condaenv.afapys2r.requirements.txt', '--exists-action=b']
Pip subprocess output:
Obtaining taming-transformers from git+https://github.com/CompVis/taming-transformers.git@master#egg=taming-transformers (from -r /media/user/Daten/localization/latent-diffusion/condaenv.afapys2r.requirements.txt (line 13))

Pip subprocess error:
ERROR: Exception:
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 171, in _merge_into_criterion
    crit = self.state.criteria[name]
KeyError: 'taming-transformers'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 322, in get_remote_url
    found_remote = remotes[0]
IndexError: list index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 224, in _main
    status = self.run(options, args)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 180, in wrapper
    return func(self, options, args)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 320, in run
    requirement_set = resolver.resolve(
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 121, in resolve
    self._result = resolver.resolve(
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 445, in resolve
    state = resolution.resolve(requirements, max_rounds=max_rounds)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 310, in resolve
    name, crit = self._merge_into_criterion(r, parent=None)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 173, in _merge_into_criterion
    crit = Criterion.from_requirement(self._p, requirement, parent)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 79, in from_requirement
    cands = build_iter_view(provider.find_matches([requirement]))
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 148, in build_iter_view
    matches = list(matches)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 255, in <genexpr>
    if constraint.is_satisfied_by(c)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/base.py", line 66, in is_satisfied_by
    return self.specifier.contains(candidate.version, prereleases=True)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 194, in version
    self._version = self.dist.parsed_version
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 239, in dist
    self._prepare()
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 226, in _prepare
    dist = self._prepare_distribution()
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 346, in _prepare_distribution
    return self._factory.preparer.prepare_editable_requirement(self._ireq)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 573, in prepare_editable_requirement
    req.update_editable(self.download_dir is None)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/req/req_install.py", line 655, in update_editable
    vcs_backend.obtain(self.source_dir, url=hidden_url)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/versioncontrol.py", line 654, in obtain
    existing_url = self.get_remote_url(dest)
  File "/home/user/anaconda3/envs/ldm/lib/python3.8/site-packages/pip/_internal/vcs/git.py", line 324, in get_remote_url
    raise RemoteNotFoundError
pip._internal.vcs.versioncontrol.RemoteNotFoundError

failed

CondaEnvException: Pip failed`

**Comment by ppwqxez** [comment]
I've had problems like your first one. But I don't know if you have the problem of prompting for a low CUDA version there? What is the version of CUDA you have installed?Thank you.
