### ISSUE TITLE
Error, no parenthesis on print

### ISSUE THREAD

**Issue by MyUsernamee** [CompVis/latent-diffusion#71]
After creating a conda env like specified in the readme and downloading the models, I can't run the text2im script, I get this error:

```Traceback (most recent call last):
  File "scripts/txt2img.py", line 10, in <module>
    from ldm.util import instantiate_from_config
  File "/home/dihydromonoxide/.local/lib/python3.8/site-packages/ldm.py", line 77
    print os.path.exists("%s.bz2"%(predictor_path))
```

To do this I ran:
```$ conda env create -f environment.yaml # To create the conda env
$ conda activate ldm # To activate it
$ mkdir -p models/ldm/text2img-large/ # To download the model
$ wget -O models/ldm/text2img-large/model.ckpt https://ommer-lab.com/files/latent-diffusion/nitro/txt2img-f8-large/model.ckpt
$ python3 scripts/txt2img.py --prompt "a virus monster is playing guitar, oil on canvas" --ddim_eta 0.0 --n_samples 4 --n_iter 4 --scale 5.0  --ddim_steps 50 # To run it
```

I am running the latest version of conda 4.12.0 and python 3.8.5.

Thank you for any help in advance! It is probably something simple!

**Comment by eformx** [comment]
did you place it in txt2Img.py?
