### ISSUE TITLE
Predictions from custom trained LDMs gives TypeError

### ISSUE THREAD

**Issue by naveedunjum** [CompVis/latent-diffusion#97]
I trained the LDM on LSUN churches and now want to use this model to predict images. However, I am getting TypeErrors on my last saved checkpoint. 
My query:` python scripts/txt2img.py --prompt "church, oil on canvas" --ddim_eta 0.0 --n_samples 4 --n_iter 4 --scale 5.0  --ddim_steps 50
`
I put my last saved checkpoint in `models/ldm/text2img-large/` and changed the config file in` txt2img.py` to` lsun_churches`.
`Training LatentDiffusion as an unconditional model.
Traceback (most recent call last):
  File "latent-diffusion/scripts/txt2img.py", line 133, in <module>
    uc = model.get_learned_conditioning(opt.n_samples * [""])
  File "latent-diffusion/ldm/models/diffusion/ddpm.py", line 558, in get_learned_conditioning
    c = self.cond_stage_model(c)
TypeError: 'NoneType' object is not callable`

Can someone help? What am i doing wrong? 
One other confusion i had, do i have train the autoencoder model as well, i assume that's for imageNet only

**Comment by naveedunjum** [comment]
@sunsq-blue, can you please post here. So what I did was , train the models with given configs for some epochs. I use the checkpointed model to sample using `python scripts/sample_diffusion.py -r models/ldm/lsun_churches256/model.ckpt -l preds -n 4 --batch_size 8 -c 500 -e 1`. But it gives me errors above. Can you please check

**Comment by bojlahg** [comment]
set batch size same as n  (4)
